import { DealTemplate } from "@/types";
import {
  Package,
  Handshake,
  DollarSign,
  ArrowLeftRight,
  PenLine,
  LucideIcon,
  FileText,
  ShieldCheck,
  Home,
  Car,
  Briefcase,
  Gift,
  Users,
  Heart,
  Star,
  Clock,
  Zap,
  Shield,
  Key,
  CreditCard,
  Building2,
  ShoppingBag,
  Laptop,
  Smartphone,
  Camera,
} from "lucide-react";

export const iconMap: Record<string, LucideIcon> = {
  Package,
  Handshake,
  DollarSign,
  ArrowLeftRight,
  PenLine,
  "file-text": FileText,
  FileText,
  ShieldCheck,
  Home,
  Car,
  Briefcase,
  Gift,
  Users,
  Heart,
  Star,
  Clock,
  Zap,
  Shield,
  Key,
  CreditCard,
  Building2,
  ShoppingBag,
  Laptop,
  Smartphone,
  Camera,
};

export const templateIconNames: Record<string, string> = {
  "payment-promise": "DollarSign",
  "item-loan": "Package",
  "service-agreement": "Briefcase",
  "event-commitment": "Clock",
  "security-deposit": "Shield",
  "handshake-deal": "Handshake",
  "rental-agreement": "Key",
  "split-expense": "Users",
  custom: "PenLine",
};

export const dealTemplates: DealTemplate[] = [
  // 1. PAYMENT PROMISE (IOU) - Most common use case
  {
    id: "payment-promise",
    name: "Payment Promise",
    description: "When someone owes you money or vice versa",
    icon: "DollarSign",
    fields: [
      {
        id: "amount",
        label: "Amount",
        type: "currency",
        placeholder: "0.00",
        required: true,
      },
      {
        id: "reason",
        label: "What is this payment for?",
        type: "text",
        placeholder: "e.g., Concert tickets, dinner bill, loan repayment",
        required: true,
      },
      {
        id: "dueDate",
        label: "Payment Due By",
        type: "date",
        required: false,
      },
      {
        id: "paymentMethod",
        label: "Preferred Payment Method",
        type: "text",
        placeholder: "e.g., Venmo, bank transfer, cash",
        required: false,
      },
    ],
  },
  // 2. ITEM LOAN - Second most common
  {
    id: "item-loan",
    name: "Item Loan",
    description: "Lend or borrow items with a clear record",
    icon: "Package",
    fields: [
      {
        id: "item",
        label: "Item Being Loaned",
        type: "text",
        placeholder: "e.g., DSLR camera, power drill, vintage jacket",
        required: true,
      },
      {
        id: "estimatedValue",
        label: "Estimated Value",
        type: "currency",
        placeholder: "0.00",
        required: true,
      },
      {
        id: "returnDate",
        label: "Return By",
        type: "date",
        required: true,
      },
      {
        id: "condition",
        label: "Current Condition",
        type: "textarea",
        placeholder: "Describe condition, any scratches, accessories included, etc.",
        required: false,
      },
      {
        id: "location",
        label: "Pickup/Return Location",
        type: "text",
        placeholder: "e.g., My apartment, your office, coffee shop on Main St",
        required: false,
      },
      {
        id: "workingCondition",
        label: "Item is in working condition",
        type: "checkbox",
        required: false,
      },
    ],
  },
  // 3. SERVICE AGREEMENT - Freelance/favor work
  {
    id: "service-agreement",
    name: "Service Agreement",
    description: "Agree on work to be done and compensation",
    icon: "Briefcase",
    fields: [
      {
        id: "serviceDescription",
        label: "Service to be Provided",
        type: "textarea",
        placeholder: "Describe the work in detail (scope, deliverables, expectations)",
        required: true,
      },
      {
        id: "compensation",
        label: "Agreed Compensation",
        type: "currency",
        placeholder: "0.00",
        required: true,
      },
      {
        id: "deadline",
        label: "Completion Deadline",
        type: "date",
        required: true,
      },
      {
        id: "notes",
        label: "Additional Terms",
        type: "textarea",
        placeholder: "Payment timeline, revision policy, or other conditions",
        required: false,
      },
      {
        id: "revisionsIncluded",
        label: "Revisions included in price",
        type: "checkbox",
        required: false,
      },
    ],
  },
  // 4. EVENT COMMITMENT - RSVP/attendance promises
  {
    id: "event-commitment",
    name: "Event Commitment",
    description: "Confirm attendance or participation in an event",
    icon: "Clock",
    fields: [
      {
        id: "eventName",
        label: "Event Name",
        type: "text",
        placeholder: "e.g., Birthday party, wedding, group trip",
        required: true,
      },
      {
        id: "eventDate",
        label: "Event Date",
        type: "date",
        required: true,
      },
      {
        id: "contribution",
        label: "My Contribution",
        type: "currency",
        placeholder: "0.00",
        required: false,
      },
      {
        id: "responsibilities",
        label: "What I'm Responsible For",
        type: "textarea",
        placeholder: "e.g., Bringing dessert, driving, organizing venue",
        required: false,
      },
    ],
  },
  // 5. DEPOSIT / SECURITY - Hold money for something
  {
    id: "security-deposit",
    name: "Security Deposit",
    description: "Document a deposit or held funds with return conditions",
    icon: "Shield",
    fields: [
      {
        id: "depositAmount",
        label: "Deposit Amount",
        type: "currency",
        placeholder: "0.00",
        required: true,
      },
      {
        id: "depositFor",
        label: "Deposit For",
        type: "text",
        placeholder: "e.g., Room rental, equipment use, event venue",
        required: true,
      },
      {
        id: "returnConditions",
        label: "Return Conditions",
        type: "textarea",
        placeholder: "Conditions under which the deposit will be refunded",
        required: true,
      },
      {
        id: "returnDate",
        label: "Expected Return Date",
        type: "date",
        required: false,
      },
      {
        id: "depositReceived",
        label: "Deposit has been received",
        type: "checkbox",
        required: false,
      },
    ],
  },
  // 6. VERBAL AGREEMENT RECORD - Capture handshake deals
  {
    id: "handshake-deal",
    name: "Handshake Deal",
    description: "Turn any verbal agreement into a written record",
    icon: "Handshake",
    fields: [
      {
        id: "agreementDetails",
        label: "The Agreement",
        type: "textarea",
        placeholder: "Describe what was agreed - who does what, any conditions, expectations",
        required: true,
      },
      {
        id: "valueInvolved",
        label: "Value Involved (if any)",
        type: "currency",
        placeholder: "0.00",
        required: false,
      },
      {
        id: "deadline",
        label: "Deadline",
        type: "date",
        required: false,
      },
      {
        id: "consequences",
        label: "What Happens If Not Fulfilled",
        type: "text",
        placeholder: "e.g., Refund issued, favor owed, no hard feelings",
        required: false,
      },
    ],
  },
  // 7. RENTAL AGREEMENT - Short-term rentals between people
  {
    id: "rental-agreement",
    name: "Rental Agreement",
    description: "Rent out or borrow items, spaces, or vehicles",
    icon: "Key",
    fields: [
      {
        id: "rentalItem",
        label: "What's Being Rented",
        type: "text",
        placeholder: "e.g., Parking spot, camera gear, vacation home",
        required: true,
      },
      {
        id: "rentalFee",
        label: "Rental Fee",
        type: "currency",
        placeholder: "0.00",
        required: true,
      },
      {
        id: "rentalPeriod",
        label: "Rental Period",
        type: "text",
        placeholder: "e.g., Jan 15-20, 2025 or 3 months starting Feb 1",
        required: true,
      },
      {
        id: "terms",
        label: "Usage Terms & Restrictions",
        type: "textarea",
        placeholder: "Any rules, restrictions, or conditions for use",
        required: false,
      },
    ],
  },
  // 8. SPLIT EXPENSE - Group purchases and shared costs
  {
    id: "split-expense",
    name: "Split Expense",
    description: "Track shared purchases and who owes what",
    icon: "Users",
    fields: [
      {
        id: "expenseFor",
        label: "What Was Purchased",
        type: "text",
        placeholder: "e.g., Groceries, group gift, Airbnb stay, dinner bill",
        required: true,
      },
      {
        id: "totalAmount",
        label: "Total Amount Paid",
        type: "currency",
        placeholder: "0.00",
        required: true,
      },
      {
        id: "theirShare",
        label: "Amount They Owe",
        type: "currency",
        placeholder: "0.00",
        required: true,
      },
      {
        id: "dueDate",
        label: "Pay Back By",
        type: "date",
        required: false,
      },
    ],
  },
];
